name: example
on:
  schedule:
    - cron: '*/1 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check Tickets
        uses: AntaresUp/melon-ticket-actions@v1.1.5
        with:
          product-id: 210230
          schedule-id: 100001
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '<@AntaresUp> 티켓사세요'
